services:

  main:
    container_name: main
    build:
      context: ./main
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./main:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - api-users
      - users-db

  api-users:
    container_name: api-users
    build:
      context: ./api-users
      dockerfile: Dockerfile
    env_file:
      - ./api-users/.env
    volumes:
      - ./api-users:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - users-db

  users-db:
    container_name: users-db
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE_USERS}
    volumes:
      - ./api-users/data/seeding.js:/docker-entrypoint-initdb.d/seeding.js
      - users-data:/data/db

  authentication-service:
    container_name: authentication-service
    build:
      context: ./authentication-service
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./authentication-service:/app
      - /app/node_modules
    ports:
      - "3002:3000"
    depends_on:
      - users-db

  authorization-service:
    container_name: authorization-service
    build:
      context: ./authorization-service
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./authorization-service:/app
      - /app/node_modules
    ports:
      - "3003:3000"
    depends_on:
      - authentication-service

  acl-service:
    container_name: acl-service
    build:
      context: ./acl-service
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./acl-service:/app
      - /app/node_modules
    ports:
      - "3004:3000"
    depends_on:
      - authorization-service

volumes:
  users-data:
